// Auto-generated by npm run prepare-supabase-config -- --env production.
// Versioned and published from main by GitHub Pages. Main requires production.
window.SUPABASE_URL = "https://dhmkhogszktonyuynpns.supabase.co";
window.SUPABASE_ANON_KEY = "sb_publishable_R_maspejLIcr9zSvbvW4Ww_mHpAysWz";
