export const URLS = Object.freeze({
  production: 'https://dhmkhogszktonyuynpns.supabase.co',
  development: 'https://xbsequfhjqdcarsidxxa.supabase.co',
});
const legacy = ['SUPER_CONCTION_STRING', 'SUPABASE_CONNECTIONSTRING'];
const removed = ['super_conction_string', 'SUPABASE_CONNECTION_STRING', 'SUPER_CONCTION', 'super_conction', 'SUPABASE_PROJECT_URL', 'SUPABASE_PROJECTURL', 'SUPABASE_PUBLISHKEY'];

export function validatePublicKey(key, url) {
  if (!key || key !== key.trim()) throw new Error('Clé publique manquante ou mal formée.');
  if (/^sb_publishable_[A-Za-z0-9_-]+$/.test(key)) return;
  try {
    const parts = key.split('.');
    if (parts.length !== 3) throw new Error();
    const payload = JSON.parse(Buffer.from(parts[1], 'base64url').toString());
    if (payload.role !== 'anon' || payload.ref !== new URL(url).hostname.split('.')[0]) throw new Error();
    if (payload.exp && payload.exp * 1000 <= Date.now()) throw new Error();
  } catch {
    throw new Error('Clé invalide : clé publique publishable ou JWT anon du projet attendu requis.');
  }
}

export function resolveConfig(env, mode) {
  if (!Object.hasOwn(URLS, mode)) throw new Error('--env production ou --env development est obligatoire.');
  const entries = Object.entries(env).filter(([, value]) => String(value).trim());
  if (mode === 'production' && entries.some(([name, value]) =>
    /supabase|super_conction/i.test(name) &&
    (/(^|_)dev(elopment)?(_|$)/i.test(name) || String(value).includes('xbsequfhjqdcarsidxxa')))) {
    throw new Error('Variable Supabase DEV détectée : génération PROD refusée.');
  }
  const present = name => env[name] !== undefined;
  if (removed.some(present)) throw new Error('Alias Supabase non pris en charge : utiliser SUPABASE_URL et SUPABASE_ANON_KEY.');
  const sources = legacy.filter(present);
  const pairPresent = present('SUPABASE_URL') || present('SUPABASE_ANON_KEY');
  if (sources.length + Number(pairPresent) !== 1) {
    throw new Error('Une seule source requise : paire SUPABASE_URL/SUPABASE_ANON_KEY OU SUPER_CONCTION_STRING OU SUPABASE_CONNECTIONSTRING. Aucun mélange autorisé.');
  }
  let url = env.SUPABASE_URL;
  let key = env.SUPABASE_ANON_KEY;
  if (sources.length) {
    const match = String(env[sources[0]]).match(/^(https:\/\/[^;|\s]+)[;|]([^;|\s]+)$/);
    if (!match) throw new Error('Chaîne de connexion invalide : https://projet.supabase.co;clé-publique attendu.');
    [, url, key] = match;
  }
  if (url !== URLS[mode]) throw new Error(`URL ${mode} attendue : ${URLS[mode]}`);
  validatePublicKey(key, url);
  return { url, key };
}

export async function verifyPublicKey({ url, key }, request = fetch) {
  const response = await request(`${url}/auth/v1/settings`, {
    headers: { apikey: key }, signal: AbortSignal.timeout(15000), redirect: 'error',
  });
  if (!response.ok) throw new Error(`Clé publique refusée par Supabase (HTTP ${response.status}).`);
  const settings = await response.json();
  if (!settings.external || typeof settings.external !== 'object') throw new Error('Réponse Supabase Auth inattendue.');
}

export function renderConfig({ url, key }, mode) {
  return `// Auto-generated by npm run prepare-supabase-config -- --env ${mode}.\n// Versioned and published from main by GitHub Pages. Main requires production.\nwindow.SUPABASE_URL = ${JSON.stringify(url)};\nwindow.SUPABASE_ANON_KEY = ${JSON.stringify(key)};\n`;
}

export function checkProductionContent(content) {
  if (content.includes('xbsequfhjqdcarsidxxa')) throw new Error('URL DEV interdite sur main.');
  const match = content.match(/^\/\/ Auto-generated[^\n]*\n\/\/ [^\n]*\nwindow\.SUPABASE_URL = ("[^"\n]*");\nwindow\.SUPABASE_ANON_KEY = ("[^"\n]*");\n$/);
  if (!match) throw new Error('Format inattendu : régénérer supabase-config.js en production.');
  const url = JSON.parse(match[1]);
  if (url !== URLS.production) throw new Error('main exige l’URL Supabase PROD.');
  validatePublicKey(JSON.parse(match[2]), url);
}
